return {
    ["Cute Ears"] = {
        ["Head"] = {
            ["mesh"] = {"rbxassetid://17618202202"},
            ["texture"] = {"rbxassetid://17411092404"},
            ["cframe"] = {CFrame.new(0, -0.8, 0)},
            ["angles"] = {CFrame.Angles(0, 0, 0)},
            ["vector_theree"] = {Vector3.new(0.78, 0.78, 0.78)}
        }
    },
    ["BlackRed Hair"] = {
        ["Head"] = {
            ["mesh"] = {"rbxassetid://18653383639"},
            ["texture"] = {"http://www.roblox.com/asset/?id=18653323611"},
            ["cframe"] = {CFrame.new(0, -0.2, 0)},
            ["angles"] = {CFrame.Angles(0, 0, 0)},
            ["vector_theree"] = {Vector3.new(1, 1, 1)}
        }
    },
    ["ManasCiel_Raphael Mask"] = {
        ["Head"] = {
            ["mesh"] = {"rbxassetid://6750850554"},
            ["texture"] = {"http://www.roblox.com/asset/?id=6783058251"},
            ["cframe"] = {CFrame.new(0.229, -0.169, 0.340)},
            ["angles"] = {CFrame.Angles(0.570, 0.590, -0.370)},
            ["vector_theree"] = {Vector3.new(0.9, 0.9, 0.9)}
        }
    }
}
